import test from 'node:test';
import assert from 'node:assert/strict';
import { isValidTransition } from '../lib/governance/lifecycle/transition-rules.js';
import { resolveReviewInterval } from '../lib/governance/review-interval.js';
import { GovernanceError } from '../lib/governance/errors.js';
import { assertScope, assertGovernanceActor, assertSuperuserOverride } from '../lib/governance/authorization.js';
const bu={id:'bu',role:'BUSINESS_UNIT_PIC',businessUnitId:'one'}; const procurement={id:'proc',role:'CORPORATE_GOVERNANCE'}; const executive={id:'exec',role:'EXECUTIVE'}; const admin={id:'admin',role:'SUPER_USER'};

test('DRAFT can be submitted', () => assert.equal(isValidTransition('DRAFT', 'SUBMITTED'), true));
test('Business workflow cannot publish a draft', () => assert.equal(isValidTransition('DRAFT', 'PUBLISHED'), false));
test('SUBMITTED can enter refinement', () => assert.equal(isValidTransition('SUBMITTED', 'REFINEMENT'), true));
test('VALIDATION can return to refinement', () => assert.equal(isValidTransition('VALIDATION', 'REFINEMENT'), true));
test('APPROVED cannot publish without READY_TO_PUBLISH', () => assert.equal(isValidTransition('APPROVED', 'PUBLISHED'), false));
test('published version may only archive', () => { assert.equal(isValidTransition('PUBLISHED', 'ARCHIVED'), true); assert.equal(isValidTransition('PUBLISHED', 'REFINEMENT'), false); });
test('version review override wins', () => { const value=resolveReviewInterval({version:{reviewIntervalMonths:6,effectiveAt:new Date('2026-01-15T00:00:00Z')},category:{reviewIntervalMonths:9},businessUnit:{defaultReviewIntervalMonths:12}}); assert.equal(value.reviewIntervalSource,'VERSION_OVERRIDE');assert.equal(value.nextReviewAt.toISOString(),'2026-07-15T00:00:00.000Z'); });
test('category interval wins over Business Unit', () => assert.equal(resolveReviewInterval({version:{},category:{reviewIntervalMonths:9},businessUnit:{defaultReviewIntervalMonths:12}}).reviewIntervalSource,'CATEGORY_CONFIGURATION'));
test('system default is twelve months', () => assert.deepEqual(resolveReviewInterval({version:{},category:null,businessUnit:null}),{reviewIntervalMonths:12,reviewIntervalSource:'SYSTEM_DEFAULT',nextReviewAt:null}));
test('domain errors have safe public codes', () => { const error=new GovernanceError('INVALID_TRANSITION','No arbitrary state jump.'); assert.equal(error.code,'INVALID_TRANSITION'); assert.equal(error.message,'No arbitrary state jump.'); });
test('BU can access its own scope',()=>assert.doesNotThrow(()=>assertScope(bu,'one')));
test('BU cannot access another scope',()=>assert.throws(()=>assertScope(bu,'two'),{code:'OUT_OF_SCOPE'}));
test('Procurement has cross-BU scope',()=>assert.doesNotThrow(()=>assertScope(procurement,'two')));
test('Executive is read-only',()=>assert.throws(()=>assertScope(executive,'one'),{code:'FORBIDDEN'}));
test('Procurement has governance authority',()=>assert.doesNotThrow(()=>assertGovernanceActor(procurement)));
test('BU lacks governance authority',()=>assert.throws(()=>assertGovernanceActor(bu),{code:'FORBIDDEN'}));
test('Executive lacks governance authority',()=>assert.throws(()=>assertGovernanceActor(executive),{code:'FORBIDDEN'}));
test('Admin needs override reason for approval',()=>assert.throws(()=>assertSuperuserOverride(admin,'APPROVED',{}),{code:'ADMIN_OVERRIDE_REASON_REQUIRED'}));
test('Admin needs supporting notes for publishing',()=>assert.throws(()=>assertSuperuserOverride(admin,'PUBLISHED',{overrideReason:'x'}),{code:'ADMIN_OVERRIDE_REASON_REQUIRED'}));
test('Admin override with evidence succeeds',()=>assert.doesNotThrow(()=>assertSuperuserOverride(admin,'PUBLISHED',{overrideReason:'x',notes:'evidence'})));
test('BU scope list grants an additional BU',()=>assert.doesNotThrow(()=>assertScope({...bu,businessUnitScopes:[{businessUnitId:'two'}]},'two')));
test('ARCHIVED cannot transition',()=>assert.equal(isValidTransition('ARCHIVED','DRAFT'),false));
test('REFINEMENT cannot become publish-ready',()=>assert.equal(isValidTransition('REFINEMENT','READY_TO_PUBLISH'),false));
test('VALIDATION can approve',()=>assert.equal(isValidTransition('VALIDATION','APPROVED'),true));
test('APPROVED can become publish-ready',()=>assert.equal(isValidTransition('APPROVED','READY_TO_PUBLISH'),true));
test('READY_TO_PUBLISH cannot direct archive-publish jump',()=>assert.equal(isValidTransition('READY_TO_PUBLISH','PUBLISHED'),false));
test('BU default wins when category missing',()=>assert.equal(resolveReviewInterval({version:{},businessUnit:{defaultReviewIntervalMonths:18}}).reviewIntervalSource,'BUSINESS_UNIT_CONFIGURATION'));
test('effective-date month resolution clamps at month end',()=>assert.equal(resolveReviewInterval({version:{effectiveAt:new Date('2026-01-31T00:00:00Z'),reviewIntervalMonths:1}}).nextReviewAt.toISOString(),'2026-02-28T00:00:00.000Z'));
test('non-superuser override is not required',()=>assert.doesNotThrow(()=>assertSuperuserOverride(procurement,'APPROVED',{})));
test('normal actor must be authenticated',()=>assert.throws(()=>assertScope(null,'one'),{code:'UNAUTHORIZED'}));
