CREATE TYPE "Role_new" AS ENUM ('SUPER_USER', 'CORPORATE_GOVERNANCE', 'BUSINESS_UNIT_PIC');

ALTER TABLE "User"
  ALTER COLUMN "role" TYPE "Role_new"
  USING (
    CASE "role"::text
      WHEN 'SUPER_USER' THEN 'SUPER_USER'
      WHEN 'BU_PIC' THEN 'BUSINESS_UNIT_PIC'
      WHEN 'COMPLIANCE_ADMIN' THEN 'CORPORATE_GOVERNANCE'
      WHEN 'COMPLIANCE_REVIEWER' THEN 'CORPORATE_GOVERNANCE'
      WHEN 'CORPORATE_PROCUREMENT' THEN 'CORPORATE_GOVERNANCE'
      WHEN 'EXECUTIVE' THEN 'CORPORATE_GOVERNANCE'
      WHEN 'IT_ADMIN' THEN 'CORPORATE_GOVERNANCE'
      ELSE 'CORPORATE_GOVERNANCE'
    END
  )::"Role_new";

DROP TYPE "Role";
ALTER TYPE "Role_new" RENAME TO "Role";
