'use client';
import { useEffect, useState } from 'react';

export default function Workspace({ params }) {
  const [data,setData]=useState(null),[refs,setRefs]=useState([]),[findings,setFindings]=useState([]),[form,setForm]=useState({title:'',category:'PROCESS_GAP',severity:'MEDIUM',observation:''}),[message,setMessage]=useState('');
  const load=async id=>{const [w,r,f]=await Promise.all([fetch(`/api/governance/refinement/${id}`),fetch(`/api/governance/refinement/${id}/references`),fetch(`/api/governance/refinement/${id}/findings`)]);const [wd,rd,fd]=await Promise.all([w.json(),r.json(),f.json()]);setData(wd.ok?wd.data:null);setRefs(rd.ok?rd.data:[]);setFindings(fd.ok?fd.data:[])};
  useEffect(()=>{params.then(({versionId})=>load(versionId));},[params]);
  const create=async e=>{e.preventDefault();const {versionId}=await params;const r=await fetch(`/api/governance/refinement/${versionId}/findings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),b=await r.json();if(!r.ok)return setMessage(b.error?.message||'Unable to save finding.');setForm({title:'',category:'PROCESS_GAP',severity:'MEDIUM',observation:''});setMessage('Finding saved.');load(versionId)};
  if(!data)return <main className="native-page">Loading Refinement workspace…</main>;
  return <main className="native-page"><header><p className="eyebrow">Human-only refinement</p><h1>{data.sop.title}</h1><p>{data.businessUnit.name} · {data.version}</p></header><section className="repository-card"><h2>Document</h2><p>{data.file.name||'No document attached'}</p>{data.file.key&&<a className="button" href={`/api/files/download?key=${encodeURIComponent(data.file.key)}&mode=inline`}>Open document securely</a>}</section><section className="repository-card"><h2>Reference set</h2>{refs.length?refs.map(r=><p key={r.id}>{r.referenceSource.title}</p>):<p>No active reference selected yet.</p>}</section><section className="repository-card"><h2>Findings</h2>{data.capabilities.canManage&&<form className="form" onSubmit={create}><input required placeholder="Finding title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>PROCESS_GAP</option><option>CONTROL_WEAKNESS</option><option>OTHER</option></select><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option><option>OBSERVATION</option></select><textarea required placeholder="Observation" value={form.observation} onChange={e=>setForm({...form,observation:e.target.value})}/><button className="button">Save Finding</button></form>}<p>{message}</p>{findings.map(f=><article key={f.id}><b>{f.title}</b><p>{f.severity} · {f.status}{f.blocking?' · Blocking':''}</p><p>{f.observation}</p></article>)}</section></main>;
}
