export const LifecycleState = Object.freeze({ DRAFT:'DRAFT', SUBMITTED:'SUBMITTED', REFINEMENT:'REFINEMENT', VALIDATION:'VALIDATION', APPROVED:'APPROVED', READY_TO_PUBLISH:'READY_TO_PUBLISH', PUBLISHED:'PUBLISHED', ARCHIVED:'ARCHIVED' });
export const transitionMatrix = Object.freeze({
  DRAFT: ['SUBMITTED', 'ARCHIVED'], SUBMITTED: ['REFINEMENT', 'ARCHIVED'], REFINEMENT: ['VALIDATION', 'ARCHIVED'],
  VALIDATION: ['REFINEMENT', 'APPROVED', 'ARCHIVED'], APPROVED: ['READY_TO_PUBLISH', 'ARCHIVED'],
  READY_TO_PUBLISH: ['ARCHIVED'], PUBLISHED: ['ARCHIVED'], ARCHIVED: []
});
export function isValidTransition(from, to) { return transitionMatrix[from]?.includes(to) || false; }
